"""add book and page

Revision ID: 8fce85b695ff
Revises: d627380aa96b
Create Date: 2023-10-09 20:53:36.123357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fce85b695ff'
down_revision = 'd627380aa96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_table',
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namespace_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespace_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_table_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_book_table_slug'), ['slug'], unique=True)

    op.create_table('page_table',
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('slug', sa.String(length=256), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_table', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_table_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_page_table_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_table_slug'))
        batch_op.drop_index(batch_op.f('ix_page_table_name'))

    op.drop_table('page_table')
    with op.batch_alter_table('book_table', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_table_slug'))
        batch_op.drop_index(batch_op.f('ix_book_table_name'))

    op.drop_table('book_table')
    # ### end Alembic commands ###
